# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App -- webApp-video-summary-api-dotnet

env:
  AZURE_CONTAINER_REGISTRY: videosummaryacr.azurecr.io
  AZURE_CONTAINER_REGISTRY_USERNAME: videosummaryacr
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/docker-login@v1
        name: Build Docker image
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ env.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.VIDEOSUMMARYACRSECRET }}
          
      - name: Push Docker image to Azure Container Registry
        run: |
          docker build video-summary-api -t ${{env.AZURE_CONTAINER_REGISTRY}}/video-summary-api:latest -t ${{ env.AZURE_CONTAINER_REGISTRY }}/video-summary-api:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/video-summary-api:${{ github.sha }}
          docker push  ${{ env.AZURE_CONTAINER_REGISTRY }}/video-summary-api:latest
          
